/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calibrate;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Caio
 */
public class Main extends javax.swing.JFrame {
   
    Point p1H = new Point();
    Point p2H = new Point();
    Point p3H = new Point();
    Point p4H = new Point();
    Point p1V = new Point();
    Point p2V = new Point();
    Point p3V = new Point();
    Point p4V = new Point();
    Point t_r = new Point();
    Point b_r = new Point();
    
    final Graphics g;
    String imagePath;
    
    final ArrayList<Point> aux = new ArrayList();
    int clicked = 0;
    int stageClicks = 4;
    int stage = 0;
    /**
     * Creates new form Main
     */
    public Main(String path) throws IOException{
        initComponents();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jTextField1.setVisible(false);
        jButton1.setEnabled(false);
        jButton2.setVisible(false);
        this.setLocationRelativeTo(getRootPane());
        g = jPanel1.getGraphics();
        imagePath = path;
        
        ImageIcon icon = new ImageIcon(imagePath);
        jLabel5.setIcon(icon);
        
        jPanel1.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if(clicked<stageClicks)
                {
                    Point p = e.getPoint();
                    aux.add(p);
                    
                    g.setColor(Color.red);
                    g.fillOval(p.x-4, p.y-4, 8, 8);
                    
                    clicked++;
                }
                if(clicked == stageClicks)
                    jButton1.setEnabled(true);
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 1246, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 706, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calibrate/calibrate_horizontal_square.png"))); // NOI18N

        jLabel1.setText("<html>Draw the <b>horizontal</b> points following the image order</html>");
        jLabel1.setToolTipText("");

        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.setMaximumSize(new java.awt.Dimension(73, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(73, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(73, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>Enter the size of the reference object (cm)</html>");
        jLabel3.setToolTipText("");

        jLabel4.setText("cm");

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jLabel3.getAccessibleContext().setAccessibleName("<html>Enter the size of the reference objetc (cm)</html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        aux.clear();
        repaint();
        jButton1.setEnabled(false);
        clicked = 0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int position = 0;
        
        if(stage == 2 && jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Enter the reference object size.");
        }
        else{
            for(Point p : aux)
            {
                if(stage == 0)
                {
                    if(position == 0)
                        p1H = p;
                    else if(position == 1)
                        p2H = p;
                    else if(position == 2)
                        p3H = p;
                    else if(position == 3)
                        p4H = p;

                    stageClicks = 4;
                    clicked = 0;
                    jLabel1.setText("<html>Draw the <b>vertical</b> points following the image order</html>");
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calibrate/calibrate_vertical_square.png")));
                    jButton1.setEnabled(false);
                    jButton2.setVisible(true);
                    repaint();
                }
                else if(stage == 1)
                {
                    if(position == 0)
                        p1V = p;
                    else if(position == 1)
                        p2V = p;
                    else if(position == 2)
                        p3V = p;
                    else if(position == 3)
                        p4V = p;

                    stageClicks = 2;
                    clicked = 0;
                    jButton1.setText("Finish");
                    jLabel1.setText("<html>Draw the <b>Reference</b> points following the image order</html>");
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calibrate/calibrate_object.png")));
                    jButton1.setEnabled(false);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jTextField1.setVisible(true);
                    repaint();
                }
                else if(stage == 2)
                {
                    if(position == 0)
                        t_r = p;
                    else if(position == 1)
                        b_r = p;
                    
                    String path = imagePath.substring(0,imagePath.lastIndexOf(File.separator))+"\\calibration";
                    FileWriter output = null;
                    try {
                        File f = new File(path);
                        f.createNewFile();
                        output = new FileWriter(f.getPath());
                        output.write("p1H = "+p1H.x+","+p1H.y+"\n");
                        output.write("p2H = "+p2H.x+","+p2H.y+"\n");
                        output.write("p3H = "+p3H.x+","+p3H.y+"\n");
                        output.write("p4H = "+p4H.x+","+p4H.y+"\n");
                        output.write("p1V = "+p1V.x+","+p1V.y+"\n");
                        output.write("p2V = "+p2V.x+","+p2V.y+"\n");
                        output.write("p3V = "+p3V.x+","+p3V.y+"\n");
                        output.write("p4V = "+p4V.x+","+p4V.y+"\n");
                        output.write("t_r = "+t_r.x+","+t_r.y+"\n");
                        output.write("b_r = "+b_r.x+","+b_r.y+"\n");
                        output.write("size = "+jTextField1.getText());
                        output.close();
                        
                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    
                    this.dispose();
                }
                position++;
            }
            aux.clear();
            stage++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stage--;
        aux.clear();
        if(stage == 0)
                {
                    stageClicks = 4;
                    clicked = 0;
                    jLabel1.setText("<html>Draw the <b>horizontal</b> points following the image order</html>");
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calibrate/calibrate_horizontal_square.png")));
                    jButton1.setEnabled(false);
                    jButton2.setVisible(false);
                    repaint();
                }
                else if(stage == 1)
                {
                    stageClicks = 4;
                    clicked = 0;
                    jButton1.setText("Next");
                    jLabel1.setText("<html>Draw the <b>vertical</b> points following the image order</html>");
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calibrate/calibrate_vertical_square.png")));
                    jButton1.setEnabled(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false);
                    jTextField1.setVisible(false);
                    repaint();
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
