# Raspberry Pi Software Build Makefile

all:
	@cd PowerAnalysisService/src && $(MAKE) all
	@cd VideoProcessingService/src && $(MAKE) all
	@cd Msp430Service/src && $(MAKE) all

install:
	@cd PowerAnalysisService/src && $(MAKE) clean
	@cd VideoProcessingService/src && $(MAKE) clean
	@cd Msp430Service/src && $(MAKE) clean

clean:
	@cd PowerAnalysisService/src && $(MAKE) clean
	@cd VideoProcessingService/src && $(MAKE) clean
	@cd Msp430Service/src && $(MAKE) clean
